# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'Vayuyan' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vayuyan
  pod 'RestKit', '~> 0.27.0'
  pod 'AFJSONRPCClient'
  pod 'DCKeyValueObjectMapping', '~> 1.5'
  pod 'DZNSegmentedControl'

  target 'VayuyanTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RestKit', '~> 0.27.0'
    pod 'AFJSONRPCClient'
    pod 'DCKeyValueObjectMapping', '~> 1.5'

  end

  target 'VayuyanUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RestKit', '~> 0.27.0'
    pod 'AFJSONRPCClient'
    pod 'DCKeyValueObjectMapping', '~> 1.5'
  end

end
